### ISSUE TITLE
Failed computing credential metadata error on Android

### ISSUE THREAD

**Issue by orhun** [dialogflow/dialogflow-java-client-v2#34]
Dialogflow works as expected with the dependencies below on Android:

```
implementation 'com.google.cloud:google-cloud-dialogflow:0.105.0-alpha'
implementation 'io.grpc:grpc-okhttp:1.23.0'
```

But if we use the current latest version (106.0-alpha), it throws `UnauthenticatedException` on the `detectIntent` function.

```
08-24 15:45:07.982 26502-26558/com.app W/System.err: com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:73)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
        at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:982)
08-24 15:45:07.992 26502-26558/com.app W/System.err:     at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:957)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:515)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
        at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
        at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
        at com.google.cloud.dialogflow.v2beta1.SessionsClient.detectIntent(SessionsClient.java:253)
        at com.app.MainActivity$RequestJavaV2Task.doInBackground(MainActivity.java:83)
        at com.app.MainActivity$RequestJavaV2Task.doInBackground(MainActivity.java:60)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    		... 3 more
    Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
        at io.grpc.Status.asRuntimeException(Status.java:533)
    	... 24 more
    Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3851)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3875)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4800)
        at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials.getRequestMetadata(ServiceAccountJwtAccessCredentials.java:346)
        at com.google.auth.Credentials.blockingGetToCallback(Credentials.java:112)
        at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials.getRequestMetadata(ServiceAccountJwtAccessCredentials.java:323)
        at io.grpc.auth.GoogleAuthLibraryCallCredentials.applyRequestMetadata(GoogleAuthLibraryCallCredentials.java:110)
        at io.grpc.CallCredentials2.applyRequestMetadata(CallCredentials2.java:58)
        at io.grpc.internal.CallCredentialsApplyingTransportFactory$CallCredentialsApplyingTransport.newStream(CallCredentialsApplyingTransportFactory.java:108)
        at io.grpc.internal.ForwardingConnectionClientTransport.newStream(ForwardingConnectionClientTransport.java:49)
        at io.grpc.internal.InternalSubchannel$CallTracingTransport.newStream(InternalSubchannel.java:632)
        at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:353)
        at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:341)
        at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:300)
    	... 7 more
    Caused by: java.lang.NullPointerException
08-24 15:45:08.002 26502-26558/com.app W/System.err:     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
        at com.google.auth.oauth2.JwtCredentials$Builder.setPrivateKeyId(JwtCredentials.java:223)
        at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials$1.load(ServiceAccountJwtAccessCredentials.java:271)
        at com.google.auth.oauth2.ServiceAccountJwtAccessCredentials$1.load(ServiceAccountJwtAccessCredentials.java:266)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3445)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2194)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2153)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043)
```

**Comment by TeunKrikke** [comment]
Hi,

If you are still experiencing this problem can you please add some of your code. I am currently working on a similar project and managed to get the authentication to work. So I would be interested to see what is happening.

**Comment by orhun** [comment]
Here's the project that I was working on: https://github.com/orhun/dialogflowbot

**Comment by TeunKrikke** [comment]
Can you try with these two library versions instead of your current ones?

```
implementation 'com.google.cloud:google-cloud-dialogflow:0.117.0-alpha'
implementation 'io.grpc:grpc-okhttp:1.25.0'
```

I compared your init code to mine and they are equivalent.

**Comment by orhun** [comment]
yeah, as soon as possible. I'll post the results.
