### ISSUE TITLE
Failed ALPN negotiation: Unable to find compatible protocol

### ISSUE THREAD

**Issue by utsukprani** [dialogflow/dialogflow-java-client-v2#36]
I have created a very simple spring boot application. 
I am trying to call my bot from my spring boot application (RestController).
I am behind my company's firewall.

OS - Windows 10 964 bit)
Java - 9.0.4
Spring Boot - 2.3.1.RELEASE

However I am getting the below exception when I run my application.
is there a way I can fix this issue as this has really halted my progress.
I am also attaching the -

- pom.xml

- java code

`2020-07-11 03:49:37.329  INFO 20704 --- [nio-8080-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-07-11 03:49:37.329  INFO 20704 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-07-11 03:49:37.343  INFO 20704 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 13 ms
Input - [will it rain in Japan tomorrow]
Session Path: projects/myweatherbot-mplvfh/agent/sessions/cdfc8b0f-b3c5-4594-9eef-3640b43c3660
2020-07-11 03:49:43.355 ERROR 20704 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol
Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]] with root cause

io.grpc.StatusRuntimeException: UNAVAILABLE: Failed ALPN negotiation: Unable to find compatible protocol
Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.30.2.jar:1.30.2]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515) ~[grpc-stub-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.30.2.jar:1.30.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
`
[demo.zip](https://github.com/dialogflow/dialogflow-java-client-v2/files/4905777/demo.zip)

**Comment by utsukprani** [comment]
Hi,
Any help or suggestions ?

**Comment by utsukprani** [comment]
Hi,
I even enabled the 8443 connector in the server.xml to support h2. But still I am getting the error. Can someone please suggest why I am getting ALPN error when calling the Google dialogflow api ?
